name: 'NDK BoringSSL Build'
on:
  push:
    branches: [ "ndk-boring" ]
  pull_request:
    branches: [ "ndk-boring" ]
jobs:
  BuildStatic:
    runs-on: windows-2022
    steps:
      - name: Set Ninja NDK
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://dl.google.com/android/repository/android-ndk-r23c-windows.zip','android-ndk.zip')
          7z x -aoa -oC:\ android-ndk.zip ; rm android-ndk.zip ; mv C:\android-ndk-r23c C:\android-ndk
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\
          git clone --depth=1 https://boringssl.googlesource.com/boringssl -b chromium-stable
          cd boringssl
          cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-24 -DCMAKE_TOOLCHAIN_FILE=C:/android-ndk/build/cmake/android.toolchain.cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:\boringssl_install
          ninja ; ninja install
          cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-24 -DCMAKE_TOOLCHAIN_FILE=C:/android-ndk/build/cmake/android.toolchain.cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:\boringssl_share_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a armv7_boringssl_ndk_static.7z C:\boringssl_install
          7z a armv7_boringssl_share_install.7z C:\boringssl_share_install
      - name: Update NDK BoringSSL Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: NDK_BoringSSL
          files: |
            armv7_boringssl_ndk_static.7z
            armv7_boringssl_share_install.7z
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: OpenSSL1_MinGW64_Static
      #     path: openssl1_mingw_static.7z
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: OpenSSL3_MinGW64_Static
      #     path: openssl3_mingw_static.7z


  # StaticShare:
  #   runs-on: windows-2019
  #   steps:
  #     - name: Set Perl
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit-portable.zip','perl.zip')
  #         7z x -aoa -oC:\strawberry-perl perl.zip ; rm perl.zip
  #         (new-object System.Net.WebClient).DownloadFile('https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip','nasm.zip')
  #         7z x -aoa -oC:\ nasm.zip ; rm nasm.zip
  #         (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-1.1.1t.tar.gz','openssl.tar.gz')
  #         7z x -aoa openssl.tar.gz ; 7z x -aoa -oC:\ openssl.tar ; rm openssl.tar.gz ; rm openssl.tar
  #         (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-3.1.0.tar.gz','openssl.tar.gz')
  #         7z x -aoa openssl.tar.gz ; 7z x -aoa -oC:\ openssl.tar ; rm openssl.tar.gz ; rm openssl.tar
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: amd64
  #         toolset: 14.2
  #     - name: Build script
  #       run: |
  #         $Env:PATH = "C:\nasm-2.16.01;C:\strawberry-perl\perl\bin;$Env:PATH"
  #         cd C:\openssl-1.1.1t
  #         perl Configure VC-WIN64A --prefix=C:\openssl1 -static
  #         nmake -j ; nmake install_sw
  #         cd C:\openssl-3.1.0
  #         perl Configure VC-WIN64A --prefix=C:\openssl3 -static
  #         nmake -j ; nmake install_sw
  #     - name: Package Directories
  #       run: |
  #         7z a openssl1_vc142_static.7z C:\openssl1
  #         7z a openssl3_vc142_static.7z C:\openssl3
  #     - name: Update OpenSSL Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: OpenSSL
  #         files: |
  #           openssl1_vc142_static.7z
  #           openssl3_vc142_static.7z
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: OpenSSL1_VC142_Static
  #         path: openssl1_vc142_static.7z
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: OpenSSL3_VC142_Static
  #         path: openssl3_vc142_static.7z

  # VC143StaticBuild:
  #   runs-on: windows-2022
  #   steps:
  #     - name: Set Perl
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit-portable.zip','perl.zip')
  #         7z x -aoa -oC:\strawberry-perl perl.zip ; rm perl.zip
  #         (new-object System.Net.WebClient).DownloadFile('https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip','nasm.zip')
  #         7z x -aoa -oC:\ nasm.zip ; rm nasm.zip
  #         (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-1.1.1t.tar.gz','openssl.tar.gz')
  #         7z x -aoa openssl.tar.gz ; 7z x -aoa -oC:\ openssl.tar ; rm openssl.tar.gz ; rm openssl.tar
  #         (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-3.1.0.tar.gz','openssl.tar.gz')
  #         7z x -aoa openssl.tar.gz ; 7z x -aoa -oC:\ openssl.tar ; rm openssl.tar.gz ; rm openssl.tar
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: amd64
  #         toolset: 14.3
  #     - name: Build script
  #       run: |
  #         $Env:PATH = "C:\nasm-2.16.01;C:\strawberry-perl\perl\bin;$Env:PATH"
  #         cd C:\openssl-1.1.1t
  #         perl Configure VC-WIN64A --prefix=C:\openssl1 -static
  #         nmake -j ; nmake install_sw
  #         cd C:\openssl-3.1.0
  #         perl Configure VC-WIN64A --prefix=C:\openssl3 -static
  #         nmake -j ; nmake install_sw
  #     - name: Package Directories
  #       run: |
  #         7z a openssl1_vc143_static.7z C:\openssl1
  #         7z a openssl3_vc143_static.7z C:\openssl3
  #     - name: Update OpenSSL Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: OpenSSL
  #         files: |
  #           openssl1_vc143_static.7z
  #           openssl3_vc143_static.7z
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: OpenSSL1_VC143_Static
  #         path: openssl1_vc143_static.7z
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: OpenSSL3_VC143_Static
  #         path: openssl3_vc143_static.7z