name: 'Static Build'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  BuildStatic:
    runs-on: windows-2019
    steps:
      - name: Set Mingw64
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-1.1.1s.tar.gz','openssl.tar.gz')
          7z x -aoa -oC:\ openssl.tar.gz
          rm openssl.tar.gz
          (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-3.0.7.tar.gz','openssl.tar.gz')
          7z x -aoa -oC:\ openssl.tar.gz
          rm openssl.tar.gz
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
      - shell: msys2 {0}
        run: |
          pacman -S --noconfirm perl git
          export PATH="/c/mingw64/bin:$PATH"
          cd /c/openssl-1.1.1s
          ./configure mingw64 --prefix=/c/openssl1 -static
          mingw32-make -j
      - name: Package Directories
        run: |
          7z a openssl1_mingw_static.7z C:\openssl1
      - uses: actions/upload-artifact@v3
        with:
          name: OpenSSL1 MinGW64 Static
          path: openssl1_mingw_static.7z
