name: 'Static Build'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  BuildStatic:
    runs-on: windows-2019
    steps:
      - name: Set Mingw64
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-1.1.1t.tar.gz','openssl.tar.gz')
          7z x -aoa openssl.tar.gz ; 7z x -aoa -oC:\ openssl.tar ; rm openssl.tar.gz ; rm openssl.tar
          (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-3.1.0.tar.gz','openssl.tar.gz')
          7z x -aoa openssl.tar.gz ; 7z x -aoa -oC:\ openssl.tar ; rm openssl.tar.gz ; rm openssl.tar
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
      - shell: msys2 {0}
        run: |
          pacman -S --noconfirm perl git
          export PATH="/c/mingw64/bin:$PATH"
          cd /c/openssl-1.1.1t
          ./configure mingw64 --prefix=/c/openssl1 -static
          mingw32-make -j
          mingw32-make install_sw
          cd /c/openssl-3.1.0
          ./configure mingw64 --prefix=/c/openssl3 -static
          mingw32-make -j
          mingw32-make install_sw
      - name: Package Directories
        run: |
          7z a openssl1_mingw_static.7z C:\openssl1
          7z a openssl3_mingw_static.7z C:\openssl3
      - name: Update OpenSSL Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: OpenSSL
          files: |
            openssl1_mingw_static.7z
            openssl3_mingw_static.7z
      - uses: actions/upload-artifact@v3
        with:
          name: OpenSSL1_MinGW64_Static
          path: openssl1_mingw_static.7z
      - uses: actions/upload-artifact@v3
        with:
          name: OpenSSL3_MinGW64_Static
          path: openssl3_mingw_static.7z


  MSVCStaticBuild:
    runs-on: windows-2019
    steps:
      - name: Set Perl
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit-portable.zip','perl.zip')
          7z x -aoa -oC:\strawberry-perl perl.zip ; rm perl.zip
          (new-object System.Net.WebClient).DownloadFile('https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip','nasm.zip')
          7z x -aoa -oC:\ nasm.zip ; rm nasm.zip
          (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-1.1.1t.tar.gz','openssl.tar.gz')
          7z x -aoa openssl.tar.gz ; 7z x -aoa -oC:\ openssl.tar ; rm openssl.tar.gz ; rm openssl.tar
          (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-3.1.0.tar.gz','openssl.tar.gz')
          7z x -aoa openssl.tar.gz ; 7z x -aoa -oC:\ openssl.tar ; rm openssl.tar.gz ; rm openssl.tar
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.2
      - name: Build script
        run: |
          $Env:PATH = "C:\nasm-2.16.01;C:\strawberry-perl\perl\bin;$Env:PATH"
          cd C:\openssl-1.1.1t
          perl Configure VC-WIN64A --prefix=C:\openssl1 -static
          nmake -j ; nmake install_sw
          cd C:\openssl-3.1.0
          perl Configure VC-WIN64A --prefix=C:\openssl3 -static
          nmake -j ; nmake install_sw
      - name: Package Directories
        run: |
          7z a openssl1_vc142_static.7z C:\openssl1
          7z a openssl3_vc142_static.7z C:\openssl3
      - name: Update OpenSSL Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: OpenSSL
          files: |
            openssl1_vc142_static.7z
            openssl3_vc142_static.7z
      - uses: actions/upload-artifact@v3
        with:
          name: OpenSSL1_VC142_Static
          path: openssl1_vc142_static.7z
      - uses: actions/upload-artifact@v3
        with:
          name: OpenSSL3_VC142_Static
          path: openssl3_vc142_static.7z

  VC143StaticBuild:
    runs-on: windows-2022
    steps:
      - name: Set Perl
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit-portable.zip','perl.zip')
          7z x -aoa -oC:\strawberry-perl perl.zip ; rm perl.zip
          (new-object System.Net.WebClient).DownloadFile('https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip','nasm.zip')
          7z x -aoa -oC:\ nasm.zip ; rm nasm.zip
          (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-1.1.1t.tar.gz','openssl.tar.gz')
          7z x -aoa openssl.tar.gz ; 7z x -aoa -oC:\ openssl.tar ; rm openssl.tar.gz ; rm openssl.tar
          (new-object System.Net.WebClient).DownloadFile('https://www.openssl.org/source/openssl-3.1.0.tar.gz','openssl.tar.gz')
          7z x -aoa openssl.tar.gz ; 7z x -aoa -oC:\ openssl.tar ; rm openssl.tar.gz ; rm openssl.tar
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build script
        run: |
          $Env:PATH = "C:\nasm-2.16.01;C:\strawberry-perl\perl\bin;$Env:PATH"
          cd C:\openssl-1.1.1t
          perl Configure VC-WIN64A --prefix=C:\openssl1 -static
          nmake -j ; nmake install_sw
          cd C:\openssl-3.1.0
          perl Configure VC-WIN64A --prefix=C:\openssl3 -static
          nmake -j ; nmake install_sw
      - name: Package Directories
        run: |
          7z a openssl1_vc143_static.7z C:\openssl1
          7z a openssl3_vc143_static.7z C:\openssl3
      - name: Update OpenSSL Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: OpenSSL
          files: |
            openssl1_vc143_static.7z
            openssl3_vc143_static.7z
      - uses: actions/upload-artifact@v3
        with:
          name: OpenSSL1_VC143_Static
          path: openssl1_vc143_static.7z
      - uses: actions/upload-artifact@v3
        with:
          name: OpenSSL3_VC143_Static
          path: openssl3_vc143_static.7z